// packages/react/src/testing.ts
import type { ReactNode } from "react"
import type { EventPayload } from "@gpuix/native"
import {
  TestRenderer,
  hasNativeTestRenderer,
  type TestWindowOptions,
} from "@gpuix/native/testing"
import { createRoot, flushSync, type Root } from "./reconciler/reconciler.js"
import { handleGpuixEvent } from "./reconciler/event-registry.js"

export * from "@gpuix/native/testing"

export interface TestRoot {
  root: Root
  renderer: TestRenderer
  render: (node: ReactNode) => void
  unmount: () => void
}

export function createTestRoot(options: TestWindowOptions = {}): TestRoot {
  let renderer!: TestRenderer
  renderer = new TestRenderer({
    ...options,
    dispatchEvent: (event: EventPayload) => {
      flushSync(() => handleGpuixEvent(event, renderer))
    },
  })
  const root = createRoot(renderer, {
    onKeyDown: options.onKeyDown,
    onKeyUp: options.onKeyUp,
    onSelectionChange: options.onSelectionChange,
  })
  const render = (node: ReactNode): void => {
    flushSync(() => root.render(node))
    renderer.flush()
  }
  return { root, renderer, render, unmount: root.unmount }
}

export { TestRenderer, hasNativeTestRenderer }

// packages/solid/src/testing.ts
import type { JSX } from "solid-js"
import {
  TestRenderer,
  hasNativeTestRenderer,
  type TestRendererOptions,
} from "@gpuix/native/testing"
import { createRoot, type Root } from "./root.js"

export * from "@gpuix/native/testing"

export interface TestRoot {
  root: Root
  renderer: TestRenderer
  render(code: () => JSX.Element): void
  flushSync<Value>(fn: () => Value): Value
  unmount(): void
}

export function createTestRoot(options: TestRendererOptions = {}): TestRoot {
  let root!: Root
  const renderer = new TestRenderer({
    ...options,
    dispatchEvent: (event) => root.dispatch(event),
  })
  root = createRoot(renderer)
  return {
    root,
    renderer,
    render(code) {
      root.render(code)
      renderer.flush()
    },
    flushSync(fn) {
      const value = root.flushSync(fn)
      renderer.flush()
      return value
    },
    unmount() {
      root.unmount()
      renderer.flush()
    },
  }
}

export { TestRenderer, hasNativeTestRenderer }
